/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const orders_Loyalty_Logic = require('./code/orders-loyalty-logic');
const orderdetails_draft_update_Logic = require('./code/orderdetails_draft_update_logic');
const orderdetails_draft_create_Logic = require('./code/orderdetails_draft_create_logic.js');


class NorthwindSrv extends LCAPApplicationService {
    async init() {

        this.on('Action1', 'Orders', async (request, next) => {
            await orders_Loyalty_Logic(request);
            return next();
        });

        this.before(['UPDATE'], 'OrderDetails.drafts', async (request) => {
            await orderdetails_draft_update_Logic(request);
        });
        this.before(['CREATE'], 'OrderDetails.drafts', async (request) => {
            await orderdetails_draft_create_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    NorthwindSrv
};